In [1]:
import numpy as np
import pandas as pd

In [193]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [180]:
# закрепим ГСЧ, чтобы знать, в какую сторону улучшать наши веса в будущем цикле
np.random.seed(10)
weights = np.random.uniform(0,1, size=(2,1))
weights

array([[0.77132064],
       [0.02075195]])

In [181]:
# выборка наблюдений и выборка меток (таргет)
training_inputs=np.array([[0,0],
                          [1,1],
                          [0,1]])
training_outputs = np.array([[0],
                             [1],
                             [1]])

In [182]:
print('входные данные: наблюдения и метки')
for x in list(zip(training_inputs, training_outputs)):
    print(x[0], x[1])

входные данные: наблюдения и метки
[0 0] [0]
[1 1] [1]
[0 1] [1]


In [186]:
# умножаем тренировочные данные на веса, получаем результат
dot_product = np.dot(training_inputs, weights)

In [187]:
# результат умножения тренировочных данных на веса
dot_product

array([[0.        ],
       [0.79207259],
       [0.02075195]])

In [188]:
# activation by sigmoid получаем результатаы
output = sigmoid(dot_product)
output

array([[0.5       ],
       [0.68827618],
       [0.5051878 ]])

In [189]:
# вычисляем ошибку
error = - (training_outputs-output) * output * (1-output)
error

array([[ 0.125     ],
       [-0.06688099],
       [-0.12368973]])

In [190]:
# пример расчёта поправки к текущим весам, коэф-т, на который надо умножить текущие веса, чтобы приблизиться к решению
adj = np.dot(training_outputs.transpose(), error)
adj

array([[-0.19057073]])

In [191]:
# рассчитываем новые веса по скорректированному коэф-ту 
weights = weights - 0.5 * adj
weights

array([[0.86660601],
       [0.11603731]])

In [192]:
# умножаем тренировочные данные на веса, получаем результат
dot_product = np.dot(training_inputs, weights)
dot_product

array([[0.        ],
       [0.98264332],
       [0.11603731]])

In [138]:
test_input = np.array([1,0])
test_output = sigmoid(np.dot(test_input, weights))
test_input, test_output

(array([1, 0]), array([0.48163437]))

In [176]:
np.random.seed(1)
weights = np.random.uniform(-1,1, size=(2,1))
weights

array([[-0.16595599],
       [ 0.44064899]])

In [170]:
# умножаем тренировочные данные на веса, получаем результат
dot_product = np.dot(training_inputs, weights)
print('текущее предсказание', dot_product)
test_output = sigmoid(np.dot(test_input, weights))
print('\n')
print(test_output)

текущее предсказание [[ 0.        ]
 [-0.35645135]
 [-0.44326123]]


[0.52168885]


In [177]:
tries = 1000
alpha = 0.01
test_input = np.array([1,0])

np.random.seed(100)
weights = np.random.uniform(-1,1, size=(2,1))

dot_product = np.dot(training_inputs, weights)
print('текущее предсказание', dot_product)
test_output = sigmoid(np.dot(test_input, weights))
print('\n')
print(test_output)

for x in range(tries):
    # умножаем тренировочные данные на веса, получаем результат
    dot_product = np.dot(training_inputs, weights)
    print(f'{x} текущее предсказание\n', dot_product)
    
    # activation by sigmoid получаем результатаы
    output = sigmoid(dot_product)
    #print('активация сигмоидом:', output)
    
    # вычисляем ошибку
    error = - (training_outputs-output) * output * (1-output)
    print('error\n', error)
    
    # пример расчёта поправки к текущим весам, коэф-т, на который надо умножить текущие веса, чтобы приблизиться к решению
    adj = np.dot(training_outputs.transpose(), error)
    #print('adjustive coefficient to correct weights', adj)
    
    # рассчитываем новые веса по скорректированному коэф-ту 
    weights = weights - alpha * adj
    #print('new weights\n', weights)
    
print('\nerror\n', error)
print('\nтекущий результат?\n', dot_product)
print('weights?\n', weights)
print('\n')
print(test_input)
test_output = sigmoid(np.dot(test_input, weights))
print(test_output)

текущее предсказание [[ 0.        ]
 [-0.35645135]
 [-0.44326123]]


[0.52168885]
0 текущее предсказание
 [[ 0.        ]
 [-0.35645135]
 [-0.44326123]]
error
 [[ 0.125     ]
 [-0.14247164]
 [-0.14501825]]
1 текущее предсказание
 [[ 0.        ]
 [-0.35070155]
 [-0.44038633]]
error
 [[ 0.125     ]
 [-0.14227718]
 [-0.14494575]]
2 текущее предсказание
 [[ 0.        ]
 [-0.34495709]
 [-0.4375141 ]]
error
 [[ 0.125     ]
 [-0.14207975]
 [-0.14487251]]
3 текущее предсказание
 [[ 0.        ]
 [-0.33921804]
 [-0.43464458]]
error
 [[ 0.125     ]
 [-0.14187938]
 [-0.14479852]]
4 текущее предсказание
 [[ 0.        ]
 [-0.33348449]
 [-0.4317778 ]]
error
 [[ 0.125     ]
 [-0.14167608]
 [-0.14472379]]
5 текущее предсказание
 [[ 0.        ]
 [-0.32775649]
 [-0.4289138 ]]
error
 [[ 0.125     ]
 [-0.14146989]
 [-0.14464832]]
6 текущее предсказание
 [[ 0.        ]
 [-0.32203412]
 [-0.42605262]]
error
 [[ 0.125     ]
 [-0.14126082]
 [-0.14457211]]
7 текущее предсказание
 [[ 0.        ]
 [-0.31631747]
 [-

 [-0.12535825]]
174 текущее предсказание
 [[ 0.        ]
 [ 0.52282707]
 [-0.00362202]]
error
 [[ 0.125     ]
 [-0.08696809]
 [-0.12522597]]
175 текущее предсказание
 [[ 0.        ]
 [ 0.52707095]
 [-0.00150008]]
error
 [[ 0.125     ]
 [-0.0866421 ]
 [-0.12509368]]
176 текущее предсказание
 [[0.        ]
 [0.53130567]
 [0.00061728]]
error
 [[ 0.125     ]
 [-0.08631694]
 [-0.12496141]]
177 текущее предсказание
 [[0.        ]
 [0.53553124]
 [0.00273006]]
error
 [[ 0.125     ]
 [-0.08599263]
 [-0.12482914]]
178 текущее предсказание
 [[0.        ]
 [0.53974767]
 [0.00483828]]
error
 [[ 0.125     ]
 [-0.08566917]
 [-0.12469688]]
179 текущее предсказание
 [[0.        ]
 [0.54395499]
 [0.00694194]]
error
 [[ 0.125     ]
 [-0.08534656]
 [-0.12456463]]
180 текущее предсказание
 [[0.        ]
 [0.54815322]
 [0.00904105]]
error
 [[ 0.125     ]
 [-0.08502482]
 [-0.1244324 ]]
181 текущее предсказание
 [[0.        ]
 [0.55234236]
 [0.01113562]]
error
 [[ 0.125     ]
 [-0.08470394]
 [-0.12430018]]
18

349 текущее предсказание
 [[0.        ]
 [1.14394059]
 [0.30693474]]
error
 [[ 0.125     ]
 [-0.04426749]
 [-0.10350872]]
350 текущее предсказание
 [[0.        ]
 [1.14689611]
 [0.3084125 ]]
error
 [[ 0.125     ]
 [-0.04410086]
 [-0.10339728]]
351 текущее предсказание
 [[0.        ]
 [1.14984607]
 [0.30988748]]
error
 [[ 0.125     ]
 [-0.04393496]
 [-0.103286  ]]
352 текущее предсказание
 [[0.        ]
 [1.15279049]
 [0.31135969]]
error
 [[ 0.125     ]
 [-0.04376978]
 [-0.10317489]]
353 текущее предсказание
 [[0.        ]
 [1.15572938]
 [0.31282914]]
error
 [[ 0.125     ]
 [-0.04360533]
 [-0.10306394]]
354 текущее предсказание
 [[0.        ]
 [1.15866277]
 [0.31429583]]
error
 [[ 0.125     ]
 [-0.04344159]
 [-0.10295316]]
355 текущее предсказание
 [[0.        ]
 [1.16159067]
 [0.31575978]]
error
 [[ 0.125     ]
 [-0.04327858]
 [-0.10284254]]
356 текущее предсказание
 [[0.        ]
 [1.16451309]
 [0.31722099]]
error
 [[ 0.125     ]
 [-0.04311627]
 [-0.10273208]]
357 текущее предсказание

544 текущее предсказание
 [[0.        ]
 [1.63350124]
 [0.55171506]]
error
 [[ 0.125     ]
 [-0.02232484]
 [-0.08475198]]
545 текущее предсказание
 [[0.        ]
 [1.63564278]
 [0.55278583]]
error
 [[ 0.125     ]
 [-0.02225274]
 [-0.08466999]]
546 текущее предсказание
 [[0.        ]
 [1.63778123]
 [0.55385506]]
error
 [[ 0.125     ]
 [-0.02218094]
 [-0.08458812]]
547 текущее предсказание
 [[0.        ]
 [1.63991661]
 [0.55492275]]
error
 [[ 0.125     ]
 [-0.02210944]
 [-0.08450638]]
548 текущее предсказание
 [[0.        ]
 [1.64204893]
 [0.55598891]]
error
 [[ 0.125     ]
 [-0.02203822]
 [-0.08442478]]
549 текущее предсказание
 [[0.        ]
 [1.64417819]
 [0.55705354]]
error
 [[ 0.125    ]
 [-0.0219673]
 [-0.0843433]]
550 текущее предсказание
 [[0.        ]
 [1.6463044 ]
 [0.55811664]]
error
 [[ 0.125     ]
 [-0.02189666]
 [-0.08426195]]
551 текущее предсказание
 [[0.        ]
 [1.64842757]
 [0.55917823]]
error
 [[ 0.125     ]
 [-0.02182631]
 [-0.08418073]]
552 текущее предсказание
 [

 [-0.07410384]]
690 текущее предсказание
 [[0.        ]
 [1.91733107]
 [0.69362998]]
error
 [[ 0.125     ]
 [-0.01431985]
 [-0.07403831]]
691 текущее предсказание
 [[0.        ]
 [1.91909823]
 [0.69451356]]
error
 [[ 0.125     ]
 [-0.01427902]
 [-0.07397288]]
692 текущее предсказание
 [[0.        ]
 [1.92086327]
 [0.69539608]]
error
 [[ 0.125     ]
 [-0.01423834]
 [-0.07390755]]
693 текущее предсказание
 [[0.        ]
 [1.92262619]
 [0.69627754]]
error
 [[ 0.125     ]
 [-0.01419781]
 [-0.07384232]]
694 текущее предсказание
 [[0.        ]
 [1.92438699]
 [0.69715794]]
error
 [[ 0.125     ]
 [-0.01415743]
 [-0.07377718]]
695 текущее предсказание
 [[0.        ]
 [1.92614568]
 [0.69803728]]
error
 [[ 0.125     ]
 [-0.0141172 ]
 [-0.07371214]]
696 текущее предсказание
 [[0.        ]
 [1.92790227]
 [0.69891558]]
error
 [[ 0.125     ]
 [-0.01407711]
 [-0.0736472 ]]
697 текущее предсказание
 [[0.        ]
 [1.92965675]
 [0.69979282]]
error
 [[ 0.125     ]
 [-0.01403717]
 [-0.07358235]]
698 теку

851 текущее предсказание
 [[0.        ]
 [2.17745813]
 [0.82369351]]
error
 [[ 0.125     ]
 [-0.00930707]
 [-0.06464582]]
852 текущее предсказание
 [[0.        ]
 [2.17893719]
 [0.82443304]]
error
 [[ 0.125     ]
 [-0.00928377]
 [-0.06459396]]
853 текущее предсказание
 [[0.        ]
 [2.18041474]
 [0.82517182]]
error
 [[ 0.125     ]
 [-0.00926055]
 [-0.06454216]]
854 текущее предсказание
 [[0.        ]
 [2.1818908 ]
 [0.82590984]]
error
 [[ 0.125     ]
 [-0.0092374 ]
 [-0.06449044]]
855 текущее предсказание
 [[0.        ]
 [2.18336536]
 [0.82664712]]
error
 [[ 0.125     ]
 [-0.00921432]
 [-0.06443879]]
856 текущее предсказание
 [[0.        ]
 [2.18483842]
 [0.82738365]]
error
 [[ 0.125     ]
 [-0.00919133]
 [-0.06438722]]
857 текущее предсказание
 [[0.        ]
 [2.18630999]
 [0.82811944]]
error
 [[ 0.125     ]
 [-0.0091684 ]
 [-0.06433571]]
858 текущее предсказание
 [[0.        ]
 [2.18778007]
 [0.82885448]]
error
 [[ 0.125     ]
 [-0.00914556]
 [-0.06428427]]
859 текущее предсказание

In [178]:
training_outputs

array([[0],
       [1],
       [1]])